# Generated by Django 3.2.9 on 2022-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BopInfo',
            fields=[
                ('user_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=11)),
                ('rate_id', models.CharField(max_length=11)),
                ('buy_in', models.IntegerField(max_length=255)),
                ('cash_out', models.IntegerField(max_length=255)),
                ('number_of_hands', models.IntegerField(max_length=255)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCategory',
            fields=[
                ('category_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=11)),
                ('category_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRate',
            fields=[
                ('rate_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=11)),
                ('rate_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
